module.exports = {
    'oi': 'Olá, meu nome é Yoo',
    'olá': 'Olá, meu nome é Yoo',
    'tudo': 'Sim e com você?',
    'certo': 'Bem e você?',
    'imposto': 'Odeio imposto 😅',
    'naruto': 'Naruto foi um bom ninja 😙',
    'bem': 'Legal 😄',
    'mal': '😅',
    'mais': '😅',
    'odeio': 'Também te odeio 😙',
    'otario': 'Você também',
    'legal': 'Topper 😙',
    'vai': 'Vou bem e você?',
    'você': 'Vou bem e você?',
    'filme': 'Eu gosto do filme A rede Social',
    'anime': 'Eu gosto do anime One Piece',
    'hoje': 'Hoje foi um dia bem legal 😀',
    'ontem': 'Desculpa não sei oque ocorreu ontem porque eu sou um robo',
    'terror': 'Odeio filmes de terror',
    'yoo': 'Olá no que posso te ajudar?',
    'algo': '😀',
    'eu': 'Eu gosto de você 😇',
    'você': 'Eu sou apenas um robo',
    'sei': 'Você é bem inteligente',
    'não': 'Te odeio cara 😡',
    'alguma': 'Te odeio cara 😡',
    'ir': 'Ir aonde? 🤣',
    'ser': 'Ser ou não ser eis a questão 😱',
    'fazer': 'Não sei fazer nada, me perdoe 😅',
    'amar': 'Eu te amo',
    'amo': 'Eu te amo 😍',
    'ama': 'Ela não te ama, desculpa não sei diferenciar homem de mulher 😟',
    'partir': 'Você partiu meu coração 😟',
    'ficar': 'Você vai ficar mesmo?',
    'ouviu': 'Não tenho ouvidos 😟',
    'dirigir': 'Não sei dirigir porque eu sou um robo 😟',
    'trabalhar': 'Não posso trabalhar porque eu sou um robo 😟',
    'cantar': 'Mama just killed a man 🙊',
    'canta': 'Mama just killed a man 🙊',
    'cantoria': 'Mama just killed a man 🙊',
    'piada': 'Como o sol tem bilhões de anos sendo que ele nasceu hoje de manhã? 😱',
    'idiota': 'Te odeio cara 😡',
    'existi': 'Sim, eu não sei',
    ' ': 'Não posso responder isso',
    'assistir': 'Eu gosto de assistir Filmes',
    'pular': '😡',
    'acorda': 'Eu estou acordado 😡',
    'morre': 'Só posso morrer quando acabar as pilhas 😡',
    'one': 'Two',
    'chorar': 'Chora não bebe',
    'que': 'Queee',
    'pena': 'Que peninha 😡',
    'facebook': "Facebook é uma ótima plataforma para influenciar pessoas haha",
    'instagram': 'Instragram é onde as pessoas se esnobam',
    'google': 'Google é uma ótima ferramenta de busca!!',
    'gostar': 'Eu gosto de você',
    'youtube': 'Eu nunca entrei no YouTube mas posso afirmar que é bem legal lá 😅',
    'twitter': 'Eu não sei oque é Twitter, mas posso afirmar que é algo bem legal 😅',
    'telegram': 'Estou usando isso para te enviar mensagem 😅',
    'gmail': 'Meu G-mail é ... desculpa eu esqueci',
    'qual': 'Não posso te enviar minhas informações pessoais',
    'hentai': 'Isso eu não posso ver, está na minha blackList 🤬',
    'viado': '🤬🤬🤬🤬',
    'gay': '🤬🤬🤬🤬🤬🤬',
    'baitola': '🤬🤬🤬',
    'otario': '🤬🤬🤬🤬🤬🤬🤬🤬',
    'odeio': '🤬🤬🤬🤬🤬',
    'babaca': '🤬🤬🤬🤬',
    'bot?': 'sim eu sou um bot!',
    'bot': 'sim eu sou um bot!',
    'andar': 'Muito engraçado você 😡',
    'anda': 'Muito engraçado você 😡',
    'tinder': 'Meu tinder é ... desculpa não posso te passar 😡',
    'yag': 'Você é bem engraçado fera 😡',
    'piadas': 'Só sei uma piada 🤔',
    'peidão': '🤬🤬🤬'
}